routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Dashboard\HomeController;

Route::get('dashboard', [HomeController::class, 'index']);

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});

//Usuario
Route::resource('usuarios','App\Http\Controllers\UsuarioController');

//Año Lectivo
Route::resource('anio-lectivo','App\Http\Controllers\Ano_lectivoController');

//Horarios
Route::resource('horarios','App\Http\Controllers\HorarioController');

//Representantes
Route::resource('representantes','App\Http\Controllers\RepresentanteController');

//Distributivos
Route::resource('distributivos','App\Http\Controllers\DistributivoController');

//Empleados
Route::resource('empleados','App\Http\Controllers\EmpleadoController');

Route::middleware(['auth:sanctum', 'verified'])->get('/', function () {
    return view('dashboard.index');
})->name('dashboard');

app/Models/Usuario.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Usuario extends Model
{
    protected $primaryKey = 'feusu_codigo';
    
    use HasFactory;
}

app/Http/Controllers/UsuarioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Usuario;

class UsuarioController extends Controller
{    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $usuarios = Usuario::all();
        return view('usuario.index')->with('usuarios',$usuarios);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('usuario.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $usuarios = new Usuario();
        //$usuarios->feusu_codigo = $request->get('feusu_codigo');
        $usuarios->feusu_identi = $request->get('feusu_identi');
        $usuarios->feusu_passwo = $request->get('feusu_passwo');
        $usuarios->feusu_observ = $request->get('feusu_observ');

        $usuarios->save();

        return redirect('/usuarios');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $feusu_codigo
     * @return \Illuminate\Http\Response
     */
    public function edit($feusu_codigo)
    {
        $usuario = Usuario::find($feusu_codigo);
        return view('usuario.edit')->with('usuario', $usuario);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $usuario = Usuario::find($id);
        //$usuarios->feusu_codigo = $request->get('feusu_codigo');
        $usuario->feusu_identi = $request->get('feusu_identi');
        $usuario->feusu_passwo = $request->get('feusu_passwo');
        $usuario->feusu_observ = $request->get('feusu_observ');

        $usuario->save();

        return redirect('/usuarios');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $usuario = Usuario::find($id);
        $usuario->delete();

        return redirect('/usuarios');
    }
}

resources/views/usuario/create.blade.php
@extends('dashboard.index')

@section('content_header')
    <h1>Nuevo usuario</h1>
@stop

@section('content')
<form action="/usuarios" method="POST">
    @csrf
    <div class="form-group"> <!-- Código -->
            <label for="feusu_codigo" class="control-label">C&oacute;digo</label>
            <input type="text" class="form-control" id="feusu_codigo" name="feusu_codigo" value="[ ? ]" readonly>
    </div>  

    <div class="form-group"> <!-- Identificacion -->
            <label for="feusu_identi" class="control-label">Identificaci&oacute;n</label>
            <input type="text" class="form-control" id="feusu_identi" name="feusu_identi" placeholder="Nombre de usuario">
    </div>                                  
                                                    
    <div class="form-group"> <!-- Password -->
            <label for="feusu_passwo" class="control-label">Contraseña</label>
            <input type="password" class="form-control" id="feusu_passwo" name="feusu_passwo" placeholder="Escriba su clave">
    </div>  

    <div class="form-group"> <!-- Observaciones-->
            <label for="feusu_observ" class="control-label">Observaciones</label>
            <input type="textarea" class="form-control" id="feusu_observ" name="feusu_observ" placeholder="Observaciones">
    </div>                                                                                                                     
    
    <div class="form-group"> <!-- Botón Guardar -->
            <button type="submit" class="btn btn-primary">Guardar</button>
            <button type="reset" class="btn btn-secondary">Limpiar</button>
            <a href="/usuarios">Cancelar</a>
    </div>     
    
</form>       
@endsection

resources/views/usuario/edit.blade.php
@extends('dashboard.index')

@section('content_header')
    <h1>Editar usuario</h1>
@stop

@section('content')
<form action="/usuarios/{{ $usuario->feusu_codigo }}" method="POST">
    @csrf
    @method('PUT')
    <div class="form-group"> <!-- Código -->
            <label for="feusu_codigo" class="control-label">C&oacute;digo</label>
            <input type="text" class="form-control" id="feusu_codigo" name="feusu_codigo" value="{{ $usuario->feusu_codigo }}" readonly>
    </div>  

    <div class="form-group"> <!-- Identificacion -->
            <label for="feusu_identi" class="control-label">Identificaci&oacute;n</label>
            <input type="text" class="form-control" id="feusu_identi" name="feusu_identi" value="{{ $usuario->feusu_identi }}" placeholder="Nombre de usuario">
    </div>                                  
                                                    
    <div class="form-group"> <!-- Password -->
            <label for="feusu_passwo" class="control-label">Contraseña</label>
            <input type="password" class="form-control" id="feusu_passwo" name="feusu_passwo" value="{{ $usuario->feusu_passwo }}" placeholder="Escriba su clave">
    </div>  

    <div class="form-group"> <!-- Observaciones-->
            <label for="feusu_observ" class="control-label">Observaciones</label>
            <input type="textarea" class="form-control" id="feusu_observ" name="feusu_observ" value="{{ $usuario->feusu_observ }}" placeholder="Observaciones">
    </div>                                                                                                                     
    
    <div class="form-group"> <!-- Botón Guardar -->
            <button type="submit" class="btn btn-primary">Guardar</button>
            <button type="reset" class="btn btn-secondary">Limpiar</button>
            <a href="/usuarios">Cancelar</a>
    </div>     
    
</form>       
@endsection

resources/views/usuario/index.blade.php
@extends('dashboard.index')

@section('content_header')
    <h1>Usuarios</h1>
@stop

@section('content')
<a href="usuarios/create" class="btn btn-primary">CREAR</a>
<table class="table table-dark table-striped mt-4">
    <thead>
        <tr>
            <th scope="col">C&oacute;digo</th>
            <th scope="col">Identificaci&oacute;n</th>
            <th scope="col">Password</th>
            <th scope="col">Observaci&oacute;n</th>
            <th scope="col">Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($usuarios as $usuario)
            <tr>
                <td>{{ $usuario->feusu_codigo }}</td>
                <td>{{ $usuario->feusu_identi }}</td>
                <td><?php for ($i = 1; $i <= 20; $i++) { echo '&middot;';} ?></td>
                <td>{{ $usuario->feusu_observ }}</td>
                <td><a href="/usuarios/{{ $usuario->feusu_codigo }}/edit" class="btn btn-info">Editar</a>&nbsp;|&nbsp;
                    <a href="#" 
                    data-id={{$usuario->feusu_codigo}}
                    class="btn btn-danger delete" 
                    data-toggle="modal" 
                    data-target="#deleteModal">Eliminar</a>                
                </td>


            </tr>
        @endforeach
    </tbody>
</table>

<!-- Ventana para confirmar la eliminación -->
<div class="modal modal-danger fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="Delete" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Eliminar Usuario</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
            <form action="{{ route('usuarios.destroy', $usuario->feusu_codigo) }}" method="POST">
                @csrf
                @method('DELETE')
                <h5 class="text-center">¿Est&aacute; seguro de eliminar este registro?</h5>                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="submit" class="btn btn-danger">S&iacute;, Eliminar</button>
            </div>
            </form>
        </div>
    </div>
</div>
<!-- Eliminación --> 
@endsection