routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Dashboard\HomeController;

Route::get('dashboard', [HomeController::class, 'index']);

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});

//Usuario
Route::resource('usuarios','App\Http\Controllers\UsuarioController');

//Año Lectivo
Route::resource('anio-lectivo','App\Http\Controllers\Ano_lectivoController');

//Horarios
Route::resource('horarios','App\Http\Controllers\HorarioController');

//Representantes
Route::resource('representantes','App\Http\Controllers\RepresentanteController');

//Distributivos
Route::resource('distributivos','App\Http\Controllers\DistributivoController');

//Empleados
Route::resource('empleados','App\Http\Controllers\EmpleadoController');

Route::middleware(['auth:sanctum', 'verified'])->get('/', function () {
    return view('dashboard.index');
})->name('dashboard');

app/Models/Ano_lectivo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Ano_lectivo extends Model
{
    protected $table = 'ano_lectivo';
    protected $primaryKey = 'feano_codigo';

    use HasFactory;
}

app/Http/Controllers/Ano_lectivoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Ano_lectivo;

class Ano_lectivoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $anio_lectivo = Ano_lectivo::all();
        return view('ano_lectivo.index')->with('anio_lectivo',$anio_lectivo);        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('ano_lectivo.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $anio_lectivo = new Ano_lectivo();
        $anio_lectivo->feano_descri = $request->get('feano_descri');

        $anio_lectivo->save();

        return redirect('/anio-lectivo');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $feano_codigo
     * @return \Illuminate\Http\Response
     */
    public function edit($feano_codigo)
    {
        $anio_lectivo = Ano_lectivo::find($feano_codigo);
        return view('ano_lectivo.edit')->with('anio_lectivo', $anio_lectivo);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $anio_lectivo = Ano_Lectivo::find($id);
        $anio_lectivo->feano_descri = $request->get('feano_descri');

        $anio_lectivo->save();

        return redirect('/anio-lectivo');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $anio_lectivo = Ano_lectivo::find($id);
        $anio_lectivo->delete();

        return redirect('/anio-lectivo');
    }
}

resources/views/ano_lectivo/create.blade.php
@extends('dashboard.index')

@section('content_header')
    <h1>Nuevo A&ntilde;o Lectivo</h1>
@stop

@section('content')
<form action="/anio-lectivo" method="POST">
    @csrf
    <div class="form-group"> <!-- Código -->
            <label for="feano_codigo" class="control-label">C&oacute;digo</label>
            <input type="text" class="form-control" id="feano_codigo" name="feano_codigo" value="[ ? ]" readonly>
    </div>  

    <div class="form-group"> <!-- Descripción -->
            <label for="feano_descri" class="control-label">Descripci&oacute;n</label>
            <input type="text" class="form-control" id="feano_descri" maxlength="15" name="feano_descri" placeholder="Escriba el periodo" required>
    </div>                                                                                     
    
    <div class="form-group"> <!-- Botón Guardar -->
            <button type="submit" class="btn btn-primary">Guardar</button>
            <button type="reset" class="btn btn-secondary">Limpiar</button>
            <a href="/anio-lectivo">Cancelar</a>
    </div>     
    
</form>       
@endsection

resources/views/ano_lectivo/edit.blade.php
@extends('dashboard.index')

@section('content_header')
    <h1>Editar A&ntilde;o Lectivo</h1>
@stop

@section('content')
<form action="/anio-lectivo/{{ $anio_lectivo->feano_codigo }}" method="POST">
    @csrf
    @method('PUT')
    <div class="form-group"> <!-- Código -->
            <label for="feano_codigo" class="control-label">C&oacute;digo</label>
            <input type="text" class="form-control" id="feano_codigo" name="feano_codigo" value="{{ $anio_lectivo->feano_codigo }}" readonly>
    </div>  
    
    <div class="form-group"> <!-- Descripción -->
        <label for="feano_descri" class="control-label">A&ntilde;o</label>
        <input type="text" class="form-control" id="feano_descri" maxlength="15" name="feano_descri" required value="{{ $anio_lectivo->feano_descri }}">
    </div> 
                                                    
    <div class="form-group"> <!-- Botón Guardar -->
            <button type="submit" class="btn btn-primary">Guardar</button>
            <button type="reset" class="btn btn-secondary">Limpiar</button>
            <a href="/anio-lectivo">Cancelar</a>
    </div>     
    
</form>       
@endsection

resources/views/ano_lectivo/index.blade.php
@extends('dashboard.index')

@section('content_header')
    <h1>A&ntilde;o Lectivo</h1>
@stop

@section('content')
<a href="anio-lectivo/create" class="btn btn-primary">CREAR</a>
<table class="table table-dark table-striped mt-4">
    <thead>
        <tr>
            <th scope="col">C&oacute;digo</th>
            <th scope="col">A&ntilde;o Lectivo</th>
            <th scope="col">Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($anio_lectivo as $anio)
            <tr>
                <td>{{ $anio->feano_codigo }}</td>
                <td>{{ $anio->feano_descri }}</td>
                <td><a href="/anio-lectivo/{{ $anio->feano_codigo }}/edit" class="btn btn-info">Editar</a>&nbsp;|&nbsp;
                    <a href="#" 
                    data-id={{$anio->feano_codigo}}
                    class="btn btn-danger delete" 
                    data-toggle="modal" 
                    data-target="#deleteModal">Eliminar</a>                
                </td>
            </tr>
        @endforeach
    </tbody>
</table>
<!-- Ventana para confirmar la eliminación -->
<div class="modal modal-danger fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="Delete" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Eliminar A&ntilde;o Lectivo</h5>
                <input id="id" name="id">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
            <form action="{{ route('anio-lectivo.destroy', 'id') }}" method="POST">
                @csrf
                @method('DELETE')
                <h5 class="text-center">¿Est&aacute; seguro de eliminar este registro?</h5>                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="submit" class="btn btn-danger">S&iacute;, Eliminar</button>
            </div>
            </form>
        </div>
    </div>
</div>
<!-- Eliminación --> 
@endsection

@yield('javascript')
<script>
    $(document).on('click','.delete',function(){
        alert('asd'));
        let id = $(this).attr('data-id');
        $('#id').val(id);
    });
</script>